apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdeploymentdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetesdeploymentdemo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: kubernetesdeploymentdemo
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      containers:
      - name: kubernetesdeploymentdemo
        image: tutum/hello-world
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: true
        resources:
          requests:
            memory: "50Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "500m"